# Docker Compose Configuration

version: '3.8'

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"
    networks:
      - microservices-network

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    ports:
      - "9092:9092"
    networks:
      - microservices-network

  user-service:
    build: ./services/user-service
    ports:
      - "8081:8081"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      - kafka
    networks:
      - microservices-network

  product-service:
    build: ./services/product-service
    ports:
      - "8082:8082"
    environment:
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=kafka:9092
      - CLOUD_SQS_PRODUCT_EVENTS_ENABLED=false
      - CLOUD_SQS_PRODUCT_EVENTS_QUEUE_URL=https://sqs.eu-west-1.amazonaws.com/904619734225/cn-course-product-events-cli
      - CLOUD_SQS_PRODUCT_EVENTS_REGION=eu-west-1
      - AWS_ACCESS_KEY_ID=AKIA5FH4JWTI6BZRPJEP
      - AWS_SECRET_ACCESS_KEY=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
    depends_on:
      - kafka
    networks:
      - microservices-network

  order-service:
    build: ./services/order-service
    ports:
      - "8083:8083"
    environment:
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=kafka:9092
      - SERVICES_USER_URL=http://user-service:8081
      - SERVICES_PRODUCT_URL=http://product-service:8082
      - CLOUD_SQS_PRODUCT_EVENTS_CONSUMER_ENABLED=false
      - CLOUD_SQS_PRODUCT_EVENTS_CONSUMER_QUEUE_URL=https://sqs.eu-west-1.amazonaws.com/904619734225/cn-course-product-events-cli
      - CLOUD_SQS_PRODUCT_EVENTS_CONSUMER_REGION=eu-west-1
      - AWS_ACCESS_KEY_ID=AKIA5FH4JWTI6BZRPJEP
      - AWS_SECRET_ACCESS_KEY=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
    depends_on:
      - kafka
      - user-service
      - product-service
    networks:
      - microservices-network

  api-gateway:
    build: ./services/api-gateway
    ports:
      - "8080:8080"
    depends_on:
      - user-service
      - product-service
      - order-service
    networks:
      - microservices-network

networks:
  microservices-network:
    driver: bridge